name: build

on:
  workflow_call

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        minecraft: [1.20.1,1.19.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: build ${{ matrix.minecraft }}
        run: ./gradlew assemble -PmcVer="${{ matrix.minecraft }}"
